version: '3'
services:

  prom:
    container_name: "pepper-metrics-demo-prom"
    image: "zrbcool/pepper-metrics-demo-prom:latest"
    ports:
     - "9090:9090"

  grafana:
    container_name: "pepper-metrics-demo-grafana"
    image: "zrbcool/pepper-metrics-demo-grafana:latest"
    ports:
     - "3000:3000"

  redis:
    container_name: "pepper-metrics-demo-redis"
    image: "redis:latest"
    ports:
      - "6379:6379"

  server:
    container_name: "pepper-metrics-demo-server"
    image: "zrbcool/pepper-metrics-demo-server:latest"
    ports:
      - "8080"
      - "8002"
      - "9146"

  client:
    container_name: "pepper-metrics-demo-client"
    image: "zrbcool/pepper-metrics-demo-client:latest"
    depends_on:
      - "server"
#    command: ["sh", "./wait-for-it.sh"]
    expose:
      - "8080"
      - "8002"
      - "9146"
