global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  external_labels:
    monitor: 'demo-prometheus'

alerting:
  alertmanagers:
  - static_configs:
#    - targets: ['172.16.11.42:9093']

rule_files:
  - "nginx.*.rule"

scrape_configs:
#  - job_name: 'pepper_exporter_k8s'
#    static_configs:
#    - targets: ['client:9146']
#    - targets: ['server:9146']

  - job_name: 'pepper_exporter_k8s'
    file_sd_configs:
      - files:
          - app.json
    relabel_configs:
    - source_labels: [__address__]
      separator: ;
      regex: (.*)
      target_label: pod
      replacement: $1
      action: replace
